# Generated by Django 3.2.5 on 2021-08-10 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectpost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmodel',
            name='members',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupmodel',
            name='questions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('ac_member', models.TextField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectpost.groupmodel')),
            ],
        ),
    ]
