# Generated by Django 3.2.5 on 2021-08-11 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectpost', '0002_auto_20210810_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmodel',
            name='groupname',
        ),
        migrations.AddField(
            model_name='groupmodel',
            name='admin',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
