# Generated by Django 3.2.5 on 2021-08-11 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectpost', '0003_auto_20210811_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmodel',
            name='password',
        ),
        migrations.AddField(
            model_name='groupmodel',
            name='join_password',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='groupmodel',
            name='screen_password',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
