# Generated by Django 3.2.5 on 2021-08-12 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectpost', '0004_auto_20210811_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='group',
            new_name='join_group',
        ),
        migrations.AddField(
            model_name='groupmodel',
            name='group_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='created_group',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='join_password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='screen_password',
            field=models.CharField(max_length=20),
        ),
    ]
