# Generated by Django 3.2.5 on 2021-08-12 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectpost', '0006_auto_20210812_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='admin',
            new_name='user',
        ),
    ]
