# Generated by Django 3.2.5 on 2021-08-12 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectpost', '0007_rename_admin_usermodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='created_group',
            field=models.TextField(default=''),
        ),
    ]
