# Generated by Django 3.2.5 on 2021-08-12 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectpost', '0010_auto_20210812_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='created_group',
            field=models.TextField(default=''),
        ),
    ]
