# Generated by Django 3.2.5 on 2021-08-12 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectpost', '0012_auto_20210812_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmodel',
            name='admin',
            field=models.CharField(default='', max_length=20),
        ),
    ]
