# Generated by Django 3.2.5 on 2021-08-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectpost', '0014_alter_questionmodel_ac_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmodel',
            name='title',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
