# Generated by Django 3.2.5 on 2021-08-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectpost', '0016_alter_questionmodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
