# Generated by Django 3.2.5 on 2021-08-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectpost', '0017_alter_questionmodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmodel',
            name='focus_question',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
