# Generated by Django 3.2.5 on 2021-08-13 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectpost', '0018_groupmodel_focus_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmodel',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='created_group',
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='submit_member',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='focus_question',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
