# Generated by Django 3.2.5 on 2021-08-14 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectpost', '0019_auto_20210813_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmodel',
            name='members',
        ),
    ]
