# Generated by Django 3.2.5 on 2021-08-15 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectpost', '0028_alter_usermodel_join_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='join_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectpost.groupmodel'),
        ),
    ]
