# Generated by Django 3.2.5 on 2021-08-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectpost', '0029_alter_usermodel_join_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmodel',
            name='ac_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
