# Generated by Django 3.2.5 on 2021-08-17 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectpost', '0031_auto_20210817_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmodel',
            name='admin_name',
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='ac_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='admin',
            field=models.CharField(default='', max_length=20),
        ),
    ]
