# Generated by Django 3.2.5 on 2021-08-17 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectpost', '0032_auto_20210817_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionmodel',
            name='ac_count',
        ),
    ]
