# Generated by Django 3.2.5 on 2021-08-20 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectpost', '0034_auto_20210817_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmodel',
            name='input',
            field=models.TextField(default=''),
        ),
    ]
